image: ruby:2.3

variables:
  JEKYLL_ENV: production

stages:
  - build

build:
  stage: build
  script:
  - apt-get update -qy
  - apt-get install -y openjdk-8-jre-headless
  - bundle install
  - echo "Adding .env"
  - echo S3_ID=${S3_ID} > .env
  - echo S3_SECRET=${S3_SECRET} >> .env
  - echo "Google Analytics inject"
  - echo ${analyticsid}
  - sed -i -e 's/UA-XXXXXXXX-X/${analyticsid}/g' _includes/google-analytics.html
  - bundle exec jekyll build
  - bundle exec s3_website install
  - java -cp $(bundle show s3_website)/*.jar s3.website.Push
  - ruby _scripts/html-proofer.rb