image: ruby:2.3

variables:
  JEKYLL_ENV: production

stages:
  - build

build:
  stage: build
  script:
  - apt-get update -qy
  - apt-get install -y openjdk-8-jre-headless
  - bundle install
  - echo "Google Analytics inject"
  - bundle exec jekyll build
  - bundle exec s3_website push
  - ruby _scripts/html-proofer.rb