image: ruby:2.3

variables:
  JEKYLL_ENV: production

stages:
  - prepare
  - build
  - test
  - deploy

prepare:
  script:
  - bundle install
  - echo "Google Analytics inject"

build:
  script:
  - bundle exec jekyll build

test:
  script:
  - ruby _scripts/html-proofer.rb

deploy:
  script:
  - bundle exec s3_website push
