image: ruby:2.3

variables:
  JEKYLL_ENV: production

stages:
  - build

build:
  stage: build
  script:
  - bundle install
  - echo "Google Analytics inject"
  - bundle exec jekyll build
  - bundle exec s3_website push
  - ruby _scripts/html-proofer.rb