markdown: redcarpet
markdown_ext: markdown,mkd,mkdn,md
highlighter: rouge
permalink: /:year/:month/:title/
safe: false
exclude: ['s3_website.yml', 'Jenkinsfile', 'README.md', 'tmp/', 'Gemfile', 'Gemfile.lock']
paginate: 5

plugins:
- jekyll-paginate
- jekyll-assets
- jekyll-extlinks

asset_bundler:
  compress:
    js: yui
    css: yui
  base_path: /bundles/
  dev: false

collections:
  videos:
    output: true
    permalink: /videos/:path/

excerpt_separator: <!--more-->

assets:
  compress:
    css: true
    js: true
  cache: _asset-cache
  prefix: "/assets"
  assets:
    - "bundle.css"
  digest: true
  sources:
    - "_assets/css"

redcarpet:
    extensions: ["footnotes"]

extlinks:
  attributes: {target: _blank, class: 'external'}
  rel_exclude: ['savjee.be']