markdown: redcarpet
markdown_ext: markdown,mkd,mkdn,md
highlighter: rouge
permalink: /:year/:month/:title/
safe: false
exclude: ['s3_website.yml']
paginate: 5

gems:
- jekyll-paginate

asset_bundler:
  compress:
    js: yui
    css: yui
  base_path: /bundles/
  dev: false

collections:
  videos:
    output: true
    permalink: /videos/:path/

excerpt_separator: <!--more-->