markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md
highlighter: rouge
permalink: /:year/:month/:title/
safe: false
exclude: ['s3_website.yml', 'Jenkinsfile', 'README.md', 'tmp/', 'Gemfile', 'Gemfile.lock', '.jekyll-cache']

pagination: 
  enabled: true
  collection: 'posts'
  permalink: '/page:num/'
  per_page: 5
  limit: 0

plugins:
- jekyll-paginate-v2
- jekyll-assets
- jekyll-extlinks

collections:
  videos:
    output: true
    permalink: /videos/:path/

  courses:
    output: true
    permalink: /courses/:path/

excerpt_separator: <!--more-->

assets:
  # compression: true
  sources:
    - "_assets/css"
    - "_assets/js"
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true

redcarpet:
    extensions: ["footnotes"]

extlinks:
  attributes: {target: _blank, class: 'external', data-no-instant: 'data-no-instant'}
  rel_exclude: ['savjee.be']